name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Lint with flake8
        run: |
          pip install --upgrade pip
          pip install flake8
          flake8 code/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install
        run: |
          pip install --upgrade pip
          cd code && pip install -e .
      - name: Test
        run: |
          pip install pytest
          cd code && pytest tests
